name: check-latest-dd-trace-java
on: [workflow_dispatch]
jobs:
  run-echo-command:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - run: echo "check latest version for dd-trace-java agent"
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Creating a pull request
        run: |
          echo "Creating a pull request"
          touch temp_file
          git checkout -b temp_pr
          git config --global user.name "gagsingh"
          git config --global user.email "gagsingh@expediagroup.com"
          git add temp_file
          git commit -m "commit made by github actions"
          git push --set-upstream origin temp_pr
          echo "Creating a pull request"
          gh api \
          -H "Accept: application/vnd.github.v3+json" \
          /repos/rickyari/simpleconfig/pulls \
          -f title='Amazing new feature'
          -f body='Please pull these awesome changes in!'
          -f head='simpleconfig/temp_pr'
          -f base='master'

