name: check-latest-dd-trace-java
on: [workflow_dispatch]
jobs:
  run-echo-command:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - run: echo "check latest version for dd-trace-java agent"
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Creating a pull request
        run: |
          echo "Creating a pull request"
          touch temp_file
          git checkout -b temp_pr
          git config --global user.name "gagsingh"
          git config --global user.email "gagsingh@expediagroup.com"
          git add temp_file
          git commit -m "commit made by github actions"
          git push --set-upstream origin temp_pr
          echo "Creating a pull request"
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pulls \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
